branch-defaults:
  master:
    environment: study-sync-prod
environment-defaults:
  study-sync-prod:
    branch: master
    repository: study-sync
global:
  application_name: study-sync
  branch: master
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: study-sync
  sc: git
  workspace_type: Application
